source "https://rubygems.org"

# Specify your gem's dependencies in display_content.gemspec
gemspec

gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"
gem "erb"
gem "install colorize"
gem 'display_content', :path => 'display_content'